- ReadMe.md
Fix for Issue #24 Discord Invite has Expired
Found a working invite link on Steam, https://steamcommunity.com/app/368620/discussions/0/1699416432431836921/
> Fix Timespinner Official Discord invite link

- ReadMe.md
- TsRandomizer.ItemTracker/TrackerRenderer.cs
- TsRandomizer/ItemTracker/ItemTrackerState.cs
- TsRandomizer/LevelObjects/Other/GyrePortalEvent.cs
- TsRandomizer/LevelObjects/Other/HistoricalDocuments.cs
- TsRandomizer/LevelObjects/Other/SaveStatue.cs
- TsRandomizer/LevelObjects/Other/YorneNPC.cs
- TsRandomizer/LevelObjects/RoomTriggers.cs
- TsRandomizer/Randomisation/ItemLocationMap.cs
- TsRandomizer/Randomisation/ItemPlacers/ArchipelagoItemLocationRandomizer.cs
- TsRandomizer/Randomisation/ItemUnlockingMap.cs
- TsRandomizer/Randomisation/Requirement.cs
- TsRandomizer/Screens/GameDifficultyMenuScreen.cs
- TsRandomizer/Screens/MinimapScreen.cs
- TsRandomizer/Screens/SaveSelectScreen.cs
- TsRandomizer/Screens/SeedSelection/SeedOptionsCollection.cs
- TsRandomizer/SeedOptions.cs
- TsRandomizer/TimeSpinnerGame.cs
- Kobo and Merchant Crow added as gating items in logic
- Bringing Kobo to the portrait room in the library spawns a portal to the Ifrit boss, with three checks
- Bringing Merchant Crow to the Historical Documents room in the lab spawns a portal to the Ravenlord boss, with three checks
- Interactions added in marked locations when Kobo/Merchant Crow not required to show requirements in game
- Gyre locations are visible on map. Checks are visible when applicable.
- Gyre entrance is open, and exit redirects to entrance instead of a Gyre boss
- 3 item checks along the Gyre were added (Gyre has same entrance requirements as Nightmare itself, and thus cannot contain progression items unless in Multiworld
- Kobo and Merchant Crow added to the item tracker
- Readme updates
> Add Gyre Archive Flag

- TsRandomizer/LevelObjects/Other/HistoricalDocuments.cs
- TsRandomizer/LevelObjects/Other/MerchantCrowNPC.cs
- TsRandomizer/LevelObjects/RoomTriggers.cs
- TsRandomizer/Randomisation/ItemLocationMap.cs
- TsRandomizer/TsRandomizer.csproj
- New classes added to solution
- Yorne does not fall through floor
- False return warps have proper animation
- Simplified dialog replace for file cabinet
- Warp shards are only sold if the Pyramid Keys are in possession (relic active but no one turns relics off)
> Gyre Animation Cleanup + Warp Shards only sold w/ Pyramid Key

- ReadMe.md
- TsRandomizer/LevelObjects/Other/GyrePortalEvent.cs
- TsRandomizer/LevelObjects/RoomTriggers.cs
- TsRandomizer/Randomisation/ItemLocationMap.cs
- TsRandomizer/TsRandomizer.csproj
Moves the Gyre main path into logic, in the crashed Military Hangar spaceship after clearing the past (an empty room that is always passed by on every seed and requires decent progression)
Gyre in ??? has been disabled again, leaving only the alternate portals open.
Safety checks (spots technically possible but lenient in logic):
- Ifrit requires AccessToPast so that they cannot block access to the past (potential to encounter them at level 2 with only dash and them having keycards, pyramid keys, etc. otherwise). they're cheeseable but they have 5000 HP so it's best to not force them without opening up a few more checks first
- Gyre requires Wheel so that you don't have to wait for Nethershade rooms to time out
-
> Move Gyre to Military Hangar

- TsRandomizer/Randomisation/ItemLocationMap.cs
As someone else told me in [this pull request](https://github.com/ArchipelagoMW/Archipelago/pull/181), this one is incorrect, you don't need DoubleJumpOfNpc here
> Remove DoubleJumpOfNpc from Struggle Juggle check

- TsRandomizer/Archipelago/LocationMap.cs
- TsRandomizer/Randomisation/ItemLocationMap.cs
- TsRandomizer/Screens/SeedSelection/SeedOptionsCollection.cs
- TsRandomizer/SeedOptions.cs
Minor description change, lore checks now describes entries in the past as "letters" to be consistent with the in-game menu.
> Change lore description text to specify 'letters'

- ReadMe.md
- TsRandomizer/LevelObjects/Other/GlowingFloorEvent.cs
- TsRandomizer/LevelObjects/Other/PanoNPC.cs
- TsRandomizer/LevelObjects/Other/SaveStatue.cs
- TsRandomizer/LevelObjects/RoomTriggers.cs
- TsRandomizer/LevelObjects/TextReplacer.cs
- TsRandomizer/Randomisation/ItemLocationMap.cs
- TsRandomizer/Randomisation/ItemPlacers/ItemLocationRandomizer.cs
- TsRandomizer/TsRandomizer.csproj
Per discussion in the Discord, this adds a warp in the pyramid pit save room that returns to the beginning of the Pyramid.
This allows:
- Lightwall climb anti-frustration, by allowing aura to be refilled at the save point between failed attempts, as you would in vanilla
- More interesting routing by allowing the two paths in the regret chest to potentially (but rarely) be in logic (on seeds with only dash/double jump up to that point)
In addition, to complete the pyramid/the last missing chest in the randomizer, the Nightmare chest has been added. It cannot contain a progression item at this time, but may provide a last minute boon for the final boss, such as a Radiant or Empire orb
> Resolve Pyramid Pit Softlock

- TsRandomizer/Randomisation/BestiaryManager.cs
- TsRandomizer/Settings/GameSettingsLoader.cs
- TsRandomizer/Settings/SettingCollection.cs
This PR adds a setting to show the items dropped by an enemy before they are dropped, as a companion to the setting that toggles bestiary entry visibility.
> Add item drop journal visibility setting

- TsRandomizer/Extensions/ScriptActionQueueExtensions.cs
- TsRandomizer/LevelObjects/Other/CutsceneForest0.cs
- TsRandomizer/LevelObjects/RoomTriggers.cs
- TsRandomizer/TsRandomizer.csproj
Instead of a harsh cut to the refugee camp, this plays the vanilla time travel cutscene when starting an inverted scene.
Also makes previously unskippable waterfall cutscene skippable.
> Play cutscene at start of Inverted seeds

- TsRandomizer/Screens/GameSettingsScreen.cs
Adds back functionality mistakenly removed in refactor https://github.com/TriumphantBass/TsRandomizer/commit/8b834a55fab367eff58bf1d980a741064096a7e2 
Allows the ability to reset the defaults for a single category without affecting values in other categories. ("Defaults" in the root still clears all)
> Add individual settings menu resets

- TsRandomizer/LevelObjects/RoomTriggers.cs
- TsRandomizer/Screens/GameplayScreen.cs
Refreshes save flag for IsVileteSaved on non-randomized boss runs
> Fix setting the IsVileteSaved flag on non-randomized boss runs

- TsRandomizer/LevelObjects/RoomTriggers.cs
Fixes issue similar to the shop where the gyre layout was the same per the same flag set regardless of seed.
> Make Gyre unique per seed not per flag set

- TsRandomizer/Screens/GameSettingsScreen.cs
Some of the bestiary entry hooks are interfering with the settings toggle for AP settings.
This reverts the UI changes to keep this page fully functional until this can be investigated further.
> Temporary revert of AP Settings UI cleanup due to toggle bug

- TsRandomizer/Extensions/Helper.cs
- TsRandomizer/IntermediateObjects/ItemIdentifier.cs
- TsRandomizer/Randomisation/BestiaryManager.cs
- TsRandomizer/Randomisation/ItemPlacers/ItemLocationRandomizer.cs
- TsRandomizer/Screens/SaveSelectScreen.cs
- TsRandomizer/Settings/GameSettingsLoader.cs
- TsRandomizer/Settings/SettingCollection.cs
This PR includes settings that change the drop rate and frequency at which items are assigned to drop slots.
By default now, rarer items have higher drop rates *and* are less likely to be placed into drop slots.
**Drop Rate Category**
- Tiered - items are scaled to their rarity, Ultra Rare 2%, all the way to Trash 16%
- Vanilla - items inherit the odds of the slot they fill
- Random - each item is assigned the drop rate of a random tier
- Fixed - see below
**Fixed Drop Rate**
Used when drop category is "Fixed", sets all drop rates to the same value
**Loot Rarity Distribution**
- By default "Ultra Rare" items are placed into slots the least often, with "Trash" items placed the most often.
- When using Random, the behavior is the same as prior to this PR, every item is equally likely for …
> Add Tier-Based Rarity and Other Drop Settings

- TsRandomizer.ItemTracker/TrackerRenderer.cs
- TsRandomizer.Tests/ItemLocationMapFixture.cs
- TsRandomizer/ItemTracker/ItemTrackerState.cs
- TsRandomizer/LevelObjects/Other/BreakableWallEvent.cs
- TsRandomizer/LevelObjects/RoomTriggers.cs
- TsRandomizer/Randomisation/ItemLocationMap.cs
- TsRandomizer/Randomisation/ItemPlacers/FullRandomItemLocationRandomizer.cs
- TsRandomizer/Randomisation/ItemPlacers/ItemLocationRandomizer.cs
- TsRandomizer/Randomisation/ItemUnlockingMap.cs
- TsRandomizer/Randomisation/Requirement.cs
- TsRandomizer/Screens/SeedSelection/SeedOptionsCollection.cs
- TsRandomizer/SeedOptions.cs
Per discussions in the Discord, the name Facebook Mode has lost its tenuous connection with the VR headset now known as the Meta Rift. Flag name has been renamed.
Minor text fixes to other flags and descriptions.
> Rename Facebook Mode

- TsRandomizer/Randomisation/ItemPlacers/ItemLocationRandomizer.cs
There does not seem to be a high demand from the community for empty chests, removing it from the filler items pool
@JarnoWesthof
> Remove Empty chests from filler pool

- TsRandomizer/LevelObjects/RoomTriggers.cs
Sets the Timespinner as used in inverted seeds to avoid issues with using it multiple times. Sets certain scenes related to the timespinner as seen in inverted mode.
> Set Timespinner as used in Inverted Seeds

- TsRandomizer/LevelObjects/Other/BossEnemy.cs
Fixes issue with Boss Rando where Genza sets the last warp room to Amadeus' Lab's entry.
> Fix warp reset after randomized Genza

- TsRandomizer/LevelObjects/Other/BossEnemy.cs
- TsRandomizer/LevelObjects/RoomTriggers.cs
- TsRandomizer/Randomisation/BestiaryManager.cs
- TsRandomizer/Randomisation/ItemLocationMap.cs
- TsRandomizer/Screens/SeedSelection/SeedOptionsCollection.cs
- TsRandomizer/SeedOptions.cs
Adds support for the **Dad Percent** flag, which makes the win condition of the randomizer beating the boss in Emperor Nuvius' location. This will trigger the AP win condition and roll credits.
If the Nightmare location is fought with this flag on, the player will be warped back to the save room, without triggering the AP win state or rolling the credits.
> Add Dad Percent Flag

- TsRandomizer/IntermediateObjects/ItemIdentifier.cs
- TsRandomizer/IntermediateObjects/SingleItemInfo.cs
- TsRandomizer/LevelObjects/ItemManipulators/TreasureChest.cs
- TsRandomizer/Randomisation/ItemPlacers/ItemLocationRandomizer.cs
- TsRandomizer/Randomisation/ItemUnlockingMap.cs
- TsRandomizer/Randomisation/TrapManager.cs
- TsRandomizer/Screens/SeedSelection/SeedOptionsCollection.cs
- TsRandomizer/SeedOptions.cs
- TsRandomizer/Settings/GameSettingsLoader.cs
- TsRandomizer/Settings/SettingCollection.cs
- TsRandomizer/TsRandomizer.csproj
- Adds trapped chests flag, which adds empty chests to the filler pool
- Available traps for empty chests can be set in Settings
- Current available traps are Sparrow, Chaos, Neurotoxin, and Poison, and can be expanded later
- If no traps are enabled in settings, the empty chests will simply be empty, no action
For potential AP traps integration in the future, it should be possible to call TrapManager directly as needed.
> Add Trapped Chests Flag and Settings

- TsRandomizer/LevelObjects/ItemManipulators/TreasureChest.cs
Performs the same sprite replacement that is seen for freestanding items.
Used for the pyramid key sprites in Unchained Keys and the trap icon in Trapped Chests
> Sprite replacement applies to treasure chest items

- TsRandomizer/SeedOptions.cs
Trapped chests was missing from the flag dictionary
> Add trapped chests to flag mapping

- TsRandomizer/LevelObjects/Other/MerchantCrowNPC.cs
This adds an offset so that the shop inventory doesn't match the drop contents of the first 8 bestiary entries in certain scenarios.
(Note this was only true when weighted drops are turned off, when drops are weighted, there is not overlap)
> Add a shop offset to mitigate cases where the shop and drops would match

- TsRandomizer/Screens/SeedSelection/SeedSelectionMenuScreen.cs
Adds functionality on the on-screen keyboard to match the functionality of the available Ctrl-C and Ctrl-V shortcuts.
> Add Copy/Paste Buttons to Seed Selection Menu

- TsRandomizer/LevelObjects/Monsters/BossEnemy.cs
- TsRandomizer/LevelObjects/Other/GlowingFloorEvent.cs
- TsRandomizer/Randomisation/BestiaryManager.cs
- TsRandomizer/RoomTriggers/Triggers/Bosses/BossRoomTrigger.cs
- TsRandomizer/RoomTriggers/Triggers/Bosses/Cantoran.cs
- TsRandomizer/RoomTriggers/Triggers/Bosses/FakeBossRoom.cs
- TsRandomizer/RoomTriggers/Triggers/MawGasArea.cs
- TsRandomizer/Screens/SeedSelection/SeedOptionsCollection.cs
- TsRandomizer/TsRandomizer.csproj
Rather than immediately triggering a boss fight with Cantoran on re-entering the room, this PR requires the player to prompt the battle to begin
To avoid issues with an increasingly complicated recursive room trigger due to sharing a room with the pink bird quest- this moves Cantoran to a new boss arena, a previously identified generic boss arena.
> Change Cantoran to be an opt-in fight

- TsRandomizer/Extensions/SettingsExtensions.cs
- TsRandomizer/Screens/GameplayScreen.cs
- TsRandomizer/Settings/GameSettingsLoader.cs
- TsRandomizer/Settings/SettingCollection.cs
Adds a new accessibility setting, where holding down the melee attack button will attack as often as possible without needing to mash.
Can be toggled during game.
> Add Melee Autofire Setting

- TsRandomizer/Extensions/LevelExtensions.cs
- TsRandomizer/Randomisation/ItemLocationMap.cs
- TsRandomizer/Randomisation/ItemUnlockingMap.cs
- TsRandomizer/Randomisation/Requirement.cs
- TsRandomizer/Randomisation/WarpNames.cs
Changes the MarkRoomAsVisited to handle edge cases where roomId does not match array index, and adds the Refugee Camp to the warp pool, as it was affected by this limitation.
For documentation completion, adds the remaining three warp rooms as a comment
> Make Greenwood Forest (Camp) a valid teleport destination

- TsRandomizer/Randomisation/BestiaryManager.cs
making weaknesses more readable and fixing bestiary description for unscaled boss rando. Now the only bestiary weirdness is when you're currently facing a boss their bestiary entry will be modified for scaling/naming purposes (their vanilla bestiary entry slot, not the slot of the boss whose location you originally entered)
> Bestiary cleanup

- TsRandomizer/LevelObjects/Monsters/BossEnemy.cs
This fixes an issue that would cause the game to crash after fighting Cantoran with certain settings. When the Cantoran fight was moved to be in a separate arena, this line https://github.com/Jarno458/TsRandomizer/blob/master/TsRandomizer/LevelObjects/Monsters/BossEnemy.cs#L60 was changed to take into account the new arena and short circuit the rest of the Initialize logic when starting the Cantoran fight. At the same time, Boss Rando was being reworked to make changes for how the vanilla boss was being looked up that relied on that same isRandomized bool to know if a specific save flag (VanillaBossId) was set, since it needs to use that now in order to know what boss we normally should've been fighting. That flag is only set here …
> Cantoran Crashing/Weirdness Fix

- TsRandomizer/Randomisation/ItemPlacers/FullRandomItemLocationRandomizer.cs
- TsRandomizer/Randomisation/ItemUnlockingMap.cs
Fixes issue where laser gates were being included as progression items in seeds that had the prism break flag turned off.
> Change how laser access items are placed

- TsRandomizer/LevelObjects/LevelObject.cs
- TsRandomizer/RoomTriggers/Triggers/LightwallClimbBoost.cs
Cleaner version of https://github.com/Jarno458/TsRandomizer/pull/154/files 
The change to level object was adding lightwall and water mask to the items given when in debug mode, as both are helpful to have when testing things.
> Add Aura Boost to Lightwall Climbs

- TsRandomizer/Randomisation/ItemLocationMap.cs
- TsRandomizer/Randomisation/ItemPlacers/FullRandomItemLocationRandomizer.cs
- TsRandomizer/Randomisation/ItemUnlockingMap.cs
- TsRandomizer/RoomTriggers/Triggers/Bosses/Genza.cs
- TsRandomizer/RoomTriggers/Triggers/LibraryRefugeeCampTeleporters.cs
- TsRandomizer/RoomTriggers/Triggers/PastTimespinnerFreeFallCutScene.cs
- TsRandomizer/Seed.cs
This sets an enum in the seed option for the starting era to reduce the complexity of our conditionals (pyramid overwriting inverted)
> Simplify Era

- ReadMe.md
- TsRandomizer.ItemTracker/TrackerRenderer.cs
- TsRandomizer/Archipelago/ItemMap.cs
- TsRandomizer/IntermediateObjects/CustomItems/CustomItem.cs
- TsRandomizer/IntermediateObjects/CustomItems/DrawbridgeKey.cs
- TsRandomizer/ItemTracker/ItemTrackerState.cs
- TsRandomizer/LevelObjects/Other/CurtainDrawbridge.cs
- TsRandomizer/LevelObjects/Other/EnvPrefabCurtainWinch.cs
- TsRandomizer/Randomisation/ItemLocationMap.cs
- TsRandomizer/Randomisation/ItemUnlockingMap.cs
- TsRandomizer/Randomisation/Requirement.cs
- TsRandomizer/Screens/SeedSelection/SeedOptionsCollection.cs
- TsRandomizer/SeedOptions.cs
- TsRandomizer/TsRandomizer.csproj
Name subject to change (the other option I considered for it was "The Gate Isn't Down").
When using the "Gate Keep" flag, the castle drawbridge starts raised and can be lowered via item, although logic will consider the raised drawbridge to be traversable with Lightwall or Celestial Sash.
This is mainly prompted by my playing one too many inverted seeds with a lengthy search for progression over the available starting checks; I find with some testing that the amount of searching decreases considerably when half of the castle isn't available from the get-go.
> New seed option: Gate Keep

- TsRandomizer/LevelObjects/Other/GlowingFloorEvent.cs
- TsRandomizer/RoomTriggers/Triggers/LabSoftlockExits.cs
- TsRandomizer/RoomTriggers/Triggers/MilitaryHangarGyreWarp.cs
- TsRandomizer/RoomTriggers/Triggers/MilitaryHangarWarpRoom.cs
The lab softlock exit previously showed up if you had Risky Warps on, regardless. 
It now requires the laser to actually be up (either via power being on, or you being in Lock Key Amadeus and lacking the requisite key)
----
Two fixes for the hangar softlock exit
- Allows hangar to be a valid level where floors are overwritten
- Entering hangar entrance from the right will refresh boss save flags
> Fix Risky Warp Softlock Exits

- TsRandomizer/Archipelago/LocationMap.cs
- TsRandomizer/Randomisation/ItemLocationMap.cs
- TsRandomizer/Settings/GameSettingsLoader.cs
There are a few new settings or flags that don't have 100% of everything they need to be supported in Archipelago, as I discovered while working on a companion pull request to this to update the apworld to include all of the recently added settings and flags. This is seemingly everything necessary to get them all working based on some local testing.
> Updates to support new flags/settings in Archipelago

- TsRandomizer.ItemTracker/TrackerRenderer.cs
Looks like this was accidentally left in in 9cd7c2814440f8dfc93e2a1b3ffcd9ae0792f7de.
> Don't always show the drawbridge key in the item tracker

- TsRandomizer/Randomisation/ItemLocationMap.cs
- TsRandomizer/RoomTriggers/Triggers/RoyalTowersDoor.cs
- TsRandomizer/Screens/SeedSelection/SeedOptionsCollection.cs
- TsRandomizer/SeedOptions.cs
- TsRandomizer/TsRandomizer.csproj
Locks Royal Tower behind a royal orb (Plasma Orb and its derivatives), as with the royal bedroom.
I'm not completely convinced of the name, but I haven't been able to think of anything better.
The idea for this came about from some gameplay experiences while testing Gate Keep, where access to the castle via Lightwall or Sash still presents the problem of still having essentially the entirety of the castle to clear. There's already precedent for having the royal orbs lock a door, so this seems to me to be a reasonable way to leverage an existing concept to provide an opportunity for breaking down the castle into more manageable chunks.
(I'm still not completely sold on the idea myself, but I think it's at least worth presenting now that it's implemented.)
> New flag: Royal Roadblock

- TsRandomizer/Randomisation/ItemLocationMap.cs
As reported and discussed on Discord - nothing at all required the Lab Access Dynamo item, even this one location which does need it for access under the circumstances.
> Fix logic for Dynamo location with Lock Key Amadeus

- TsRandomizer/Randomisation/ItemLocationMap.cs
This is an edge case that was uncovered during some Archipelago play which also turns out to be present in the base randomiser.
MilitaryHangarGyreWarp only places the Gyre entrance when all three lasers are gone; accessing the room from the lab side without the lasers being down does not place the Gyre entrance, but logic assumed that Gyre entrance was available if you could get there at all.
Fix by ensuring that Gyre is only in logic when the lasers are down so that the gate exists.
(I've made a corresponding change in the AP pull request.)
> Fix Gyre access logic when Risky Warps takes you past the lasers

- TsRandomizer/Randomisation/ItemLocationMap.cs
Per discussion on Discord, if we get the warp to Maw cave, this location is not considered to be in logic without double jump; it's quite accessible without double jump (even if it necessitates fighting through a room with several enemies to do so).
Notably, the apworld logic for this check does not require double jump to get to the location, which I'd argue is correct.
> Adjust logic for lore check in Maw cave

- TsRandomizer/Extensions/SettingsExtensions.cs
- TsRandomizer/IntermediateObjects/CustomItems/CustomItem.cs
- TsRandomizer/IntermediateObjects/CustomItems/SpiderTrap.cs
- TsRandomizer/Randomisation/ItemPlacers/FullRandomItemLocationRandomizer.cs
- TsRandomizer/Settings/GameSettingsLoader.cs
- TsRandomizer/Settings/SettingCollection.cs
- TsRandomizer/TsRandomizer.csproj
A Spider Trap spawns two Hell Gazers, scaled to the stats of Flesh Arachnids so they're less threatening if encountered early, to the left and right of the player - about as far out as the two Meteor Sparrows from a Sparrow Trap would spawn out, but closer if there's a wall in that direction.
Nasty surprise if you activate one while dashing past a check, and probably less likely to result in weird issues than Throw Stun Traps seem to be.
> Spider traps

- TsRandomizer/Extensions/LevelExtensions.cs
- TsRandomizer/RoomTriggers/Triggers/AncientPyramidPitWarp.cs
- TsRandomizer/RoomTriggers/Triggers/LabSoftlockExits.cs
- TsRandomizer/RoomTriggers/Triggers/MilitaryHangarGyreWarp.cs
- TsRandomizer/RoomTriggers/Triggers/MilitaryHangarWarpRoom.cs
Fixes an error seen where entering the hangar from from the left with Risky Warps on and the lasers up could pre-emptively trigger a warp due to a cutscene interfering with the softlock prevention.
As softlock prevention is only relevant if you are on the wrong side of the lasers (due to a risky warp), this does not spawn it if you already have access to the warp room- i.e. the room you would enter from the left.
> Fix for Risky Warp Softlocks

- ReadMe.md
The install instructions as they are do not work on the GOG mac version, and I suspect the Steam mac version as well; this looks to correct that. While I'd like to streamline the installation process and make archipelago connection work out of the box, this would take more time and open cans of worms like "change the MonoKickstart stuff without breaking Linux," so I figure it's best to _just_ update readme.md with quick and dirty instructions before getting to that.
I'll need a guinea pig with the Steam version to check how well this works, since I don't have the Steam version to test and Steam's DRM/overlay/etc might mess with things.
> Mac Instructions/Installation

- TsRandomizer/Randomisation/OrbDamageManager.cs
Fixes an issue where orb, spell, and ring names were not clearing suffixes between runs and other scenarios, leading to several cases of double applied titles like `(+) (-)` and similar issues. Resolved by ensuring the suffixes are cleared when doing the damage substitution.
> Clear Orb Names in Damage Rando

- TsRandomizer/Randomisation/ItemLocationMap.cs
These two checks are in the upper courtyard and as such need infinite vertical
> Fix logic for Tower Courtyard Lanterns

- ReadMe.md
- TsRandomizer/LevelObjects/Monsters/BossEnemy.cs
- TsRandomizer/Screens/FeatsMenuCollection.cs
- TsRandomizer/Screens/GameSettingsScreen.cs
- TsRandomizer/Seed.cs
This PR replaces the "Quests" and "Feats" menus in the journal which are unused in the randomizer with "Statistics", which can show information about the seed, and "Objectives" which shows win conditions
While "Objectives" currently has a single "Goal" objective, representing the two win states, the motivator for changing this menu is to support an upcoming win state where the goal is to to complete a number of additional tasks from a provide list before performing the goal state; these tasks would include tasks that are currently feats and quests, which is why those menus are being replaced.
As this is a much more involved feature, this will be worked on later, but the UI changes could be leveraged now with our current win conditions.
> Show Goal and Statistics in the Journal
