Jarno458/TsRandomizer

- TsRandomizer/Archipelago/LocationMap.cs
- TsRandomizer/Archipelago/SlotDataParser.cs
- TsRandomizer/LevelObjects/ItemManipulators/JournalMemoryEvent+JournalLetterEvent.cs
- TsRandomizer/Randomisation/ItemLocationMap.cs
- TsRandomizer/Randomisation/ItemUnlockingMap.cs
- TsRandomizer/Randomisation/Requirement.cs
- TsRandomizer/Screens/SeedSelection/SeedOptionsCollection.cs
- TsRandomizer/SeedOptions.cs
- TsRandomizer/TsRandomizer.csproj
- Adds new flag, **Lore Checks**
- - Journal (past) and Memory (present) lore items are included as check locations, adding 22 additional checks when the flag is on
> Add Lore Checks Flag

- ReadMe.md
Lore's in, removing todo from the readme
> Remove Lore drops from TODO

- ReadMe.md
Minor touch up on some portions of the readme that were slightly out of date; namely the requirements section, as it mentioned the internal name EssenceOfSpace and was also written before any keycard flags were created
> Minor Readme changes

- TsRandomizer/Extensions/TextReplacer.cs
Fixes crashes caused by unimplemented hints
> Remove Hint System causing crashes

- TsRandomizer/Archipelago/LocationMap.cs
Adds lore locations to Archipelago's Location Map
> Add Lore Check locations to Archipelago

- TsRandomizer/Randomisation/ItemLocationMap.cs
As suggested by RokonShimo the Download checks should have the names like the Lore checks do.
> Added Lore names to Download checks

- TsRandomizer/Drawables/ArchipelagoRepresentation.cs
- TsRandomizer/Screens/SaveSelectScreen.cs
- Added Archipelago save info to the save selection screen
- Shows the saved Server and Username
- Accessible by holding Left Shoulder button on a save file
> Archipelago save info

- TsRandomizer/Extensions/Helper.cs
Removes the item "Nothing" from shops and enemy drops
> Removes Nothing from shop/drop loot pool

- TsRandomizer/LevelObjects/RoomTriggers.cs
> Change "forfeit" verbiage to "release" in sending items prompt at end of game.

- TsRandomizer/RoomTriggers/Triggers/Bosses/BossRoomTrigger.cs
Fixes the incorrect vanilla boss being set for the Emperor Nuvius room
> Fix Emperor Nuvius Warp

- TsRandomizer/RoomTriggers/Triggers/Bosses/SimpleBossTrigger.cs
Fixes Azure Queen warp missing from refactored room triggers
> Add missing Azure Queen warp

- TsRandomizer.ItemTracker/TrackerRenderer.cs
- TsRandomizer/Randomisation/ItemLocationMap.cs
- Make tracker display non-conditional 
- Fix mislabeled warp gate
> Fixes to Unchained Keys Flags

- TsRandomizer/IntermediateObjects/ItemIdentifier.cs
- TsRandomizer/Localizer.cs
- TsRandomizer/Randomisation/ItemUnlockingMap.cs
Fixes issue with Speaker being null for ghost text displayed during Unchained Keys messages
Also fixes invisible/mismatched sprites for the dummy map reveal items
> Fix Unchained keys Buys

- TsRandomizer/LevelObjects/Other/SaveStatue.cs
- TsRandomizer/Settings/SettingCollection.cs
added setting to disable all save points
> broken saves setting (weff hates the players)

- TsRandomizer/IntermediateObjects/CustomItems/Trap.cs
Adds back trap pickup noise that was missed during merge
> Play sound on trap pickup

- TsRandomizer/Randomisation/ItemUnlockingMap.cs
- TsRandomizer/Screens/SaveSelectScreen.cs
Adds a section in the spoiler log to show where warps lead
> Log warps in spoiler log

- TsRandomizer/Extensions/SettingsExtensions.cs
- TsRandomizer/LevelObjects/Monsters/BossEnemy.cs
- TsRandomizer/LevelObjects/Other/CutsceneCavesPast5.cs
- TsRandomizer/Randomisation/BestiaryManager.cs
- TsRandomizer/RoomTriggers/Triggers/Bosses/BossRoomTrigger.cs
- TsRandomizer/Settings/GameSettingObjects/BossRandoOverridesSetting.cs
- TsRandomizer/Settings/GameSettingsLoader.cs
- TsRandomizer/Settings/SettingCollection.cs
Adding some new types of Boss Shuffling including:
- Chaos
- All bosses are replaced randomly with the possibility of duplicate bosses
- ![image](https://github.com/Jarno458/TsRandomizer/assets/856721/62a6a1a5-67cc-4857-8a6b-082c36317534)
- Singularity
- All bosses are replaced with the same random boss
- ![image](https://github.com/Jarno458/TsRandomizer/assets/856721/802c111f-176d-4a28-901b-9f63d96cc769)
> Adding new Boss Shuffle types

- TsRandomizer/LevelObjects/Monsters/BossEnemy.cs
- TsRandomizer/Randomisation/BestiaryManager.cs
Fixing crash in bestiary when certain bosses are in the prince nuvius spot. Showing correct weaknesses in bestiary for randomized bosses
> Bestiary Fixes

- TsRandomizer/Randomisation/ItemLocationMap.cs
- TsRandomizer/RoomTriggers/Triggers/LibraryRefugeeCampTeleporters.cs
- TsRandomizer/Screens/SeedSelection/SeedOptionsCollection.cs
- TsRandomizer/SeedOptions.cs
> Shorten Name for Past Wheel and Spindle Warp Flag

- TsRandomizer/TsRandomizer.csproj
Includes room trigger in solution
> Fix Lightwall Room Trigger

- TsRandomizer/Archipelago/ItemMap.cs
- TsRandomizer/Extensions/SettingsExtensions.cs
- TsRandomizer/IntermediateObjects/CustomItems/CustomItem.cs
- TsRandomizer/IntermediateObjects/CustomItems/LightsOutTrap.cs
- TsRandomizer/IntermediateObjects/CustomItems/PalmPunchTrap.cs
- TsRandomizer/Randomisation/ItemPlacers/FullRandomItemLocationRandomizer.cs
- TsRandomizer/Settings/SettingCollection.cs
- TsRandomizer/TsRandomizer.csproj
Adds two new traps, one which darkens the entire level until a room reset, and the other which makes Lunais do her iconic 'this is serious' palm punch animation
> Add Lights Out and Palm Punch Traps

- TsRandomizer/Archipelago/LocationMap.cs
- TsRandomizer/Randomisation/ItemLocationMap.cs
Fixes in lantern logic found while integrating with AP
> Lantern Fixes

- ReadMe.md
- TsRandomizer/LevelObjects/LevelObject.cs
- TsRandomizer/LevelObjects/Other/SaveStatue.cs
- TsRandomizer/Randomisation/ItemLocationMap.cs
- TsRandomizer/RoomTriggers/Triggers/LibrarySoftlockExits.cs
- TsRandomizer/Screens/MinimapScreen.cs
- TsRandomizer/TsRandomizer.csproj
Adds platforms, re-enables the save point, and puts items back in logic with only a single jump.
> Resolve Varndagroth Softlock
